<template>
  <SampleHeader label="Caret Color Samples" />
  <SampleRow title="caret-amber"
    ><CaretSample
      class="caret-amber-[25] outline-amber-[25] [&_input:focus]:outline-amber-[25]"
      text="caret-amber-[25]"
      bgColor="dark" /><CaretSample
      class="caret-amber-[150] outline-amber-[150] [&_input:focus]:outline-amber-[150]"
      text="caret-amber-[150]"
      bgColor="dark" /><CaretSample
      class="caret-amber-[250] outline-amber-[250] [&_input:focus]:outline-amber-[250]"
      text="caret-amber-[250]"
      bgColor="dark" /><CaretSample
      class="caret-amber-[350] outline-amber-[350] [&_input:focus]:outline-amber-[350]"
      text="caret-amber-[350]"
      bgColor="dark" /><CaretSample
      class="caret-amber-[450] outline-amber-[450] [&_input:focus]:outline-amber-[450]"
      text="caret-amber-[450]"
      bgColor="light" /><CaretSample
      class="caret-amber-[550] outline-amber-[550] [&_input:focus]:outline-amber-[550]"
      text="caret-amber-[550]"
      bgColor="light" /><CaretSample
      class="caret-amber-[650] outline-amber-[650] [&_input:focus]:outline-amber-[650]"
      text="caret-amber-[650]"
      bgColor="light" /><CaretSample
      class="caret-amber-[750] outline-amber-[750] [&_input:focus]:outline-amber-[750]"
      text="caret-amber-[750]"
      bgColor="light" /><CaretSample
      class="caret-amber-[850] outline-amber-[850] [&_input:focus]:outline-amber-[850]"
      text="caret-amber-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-blue"
    ><CaretSample
      class="caret-blue-[25] outline-blue-[25] [&_input:focus]:outline-blue-[25]"
      text="caret-blue-[25]"
      bgColor="dark" /><CaretSample
      class="caret-blue-[150] outline-blue-[150] [&_input:focus]:outline-blue-[150]"
      text="caret-blue-[150]"
      bgColor="dark" /><CaretSample
      class="caret-blue-[250] outline-blue-[250] [&_input:focus]:outline-blue-[250]"
      text="caret-blue-[250]"
      bgColor="light" /><CaretSample
      class="caret-blue-[350] outline-blue-[350] [&_input:focus]:outline-blue-[350]"
      text="caret-blue-[350]"
      bgColor="light" /><CaretSample
      class="caret-blue-[450] outline-blue-[450] [&_input:focus]:outline-blue-[450]"
      text="caret-blue-[450]"
      bgColor="light" /><CaretSample
      class="caret-blue-[550] outline-blue-[550] [&_input:focus]:outline-blue-[550]"
      text="caret-blue-[550]"
      bgColor="light" /><CaretSample
      class="caret-blue-[650] outline-blue-[650] [&_input:focus]:outline-blue-[650]"
      text="caret-blue-[650]"
      bgColor="light" /><CaretSample
      class="caret-blue-[750] outline-blue-[750] [&_input:focus]:outline-blue-[750]"
      text="caret-blue-[750]"
      bgColor="light" /><CaretSample
      class="caret-blue-[850] outline-blue-[850] [&_input:focus]:outline-blue-[850]"
      text="caret-blue-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-cyan"
    ><CaretSample
      class="caret-cyan-[25] outline-cyan-[25] [&_input:focus]:outline-cyan-[25]"
      text="caret-cyan-[25]"
      bgColor="dark" /><CaretSample
      class="caret-cyan-[150] outline-cyan-[150] [&_input:focus]:outline-cyan-[150]"
      text="caret-cyan-[150]"
      bgColor="dark" /><CaretSample
      class="caret-cyan-[250] outline-cyan-[250] [&_input:focus]:outline-cyan-[250]"
      text="caret-cyan-[250]"
      bgColor="dark" /><CaretSample
      class="caret-cyan-[350] outline-cyan-[350] [&_input:focus]:outline-cyan-[350]"
      text="caret-cyan-[350]"
      bgColor="light" /><CaretSample
      class="caret-cyan-[450] outline-cyan-[450] [&_input:focus]:outline-cyan-[450]"
      text="caret-cyan-[450]"
      bgColor="light" /><CaretSample
      class="caret-cyan-[550] outline-cyan-[550] [&_input:focus]:outline-cyan-[550]"
      text="caret-cyan-[550]"
      bgColor="light" /><CaretSample
      class="caret-cyan-[650] outline-cyan-[650] [&_input:focus]:outline-cyan-[650]"
      text="caret-cyan-[650]"
      bgColor="light" /><CaretSample
      class="caret-cyan-[750] outline-cyan-[750] [&_input:focus]:outline-cyan-[750]"
      text="caret-cyan-[750]"
      bgColor="light" /><CaretSample
      class="caret-cyan-[850] outline-cyan-[850] [&_input:focus]:outline-cyan-[850]"
      text="caret-cyan-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-emerald"
    ><CaretSample
      class="caret-emerald-[25] outline-emerald-[25] [&_input:focus]:outline-emerald-[25]"
      text="caret-emerald-[25]"
      bgColor="dark" /><CaretSample
      class="caret-emerald-[150] outline-emerald-[150] [&_input:focus]:outline-emerald-[150]"
      text="caret-emerald-[150]"
      bgColor="dark" /><CaretSample
      class="caret-emerald-[250] outline-emerald-[250] [&_input:focus]:outline-emerald-[250]"
      text="caret-emerald-[250]"
      bgColor="dark" /><CaretSample
      class="caret-emerald-[350] outline-emerald-[350] [&_input:focus]:outline-emerald-[350]"
      text="caret-emerald-[350]"
      bgColor="light" /><CaretSample
      class="caret-emerald-[450] outline-emerald-[450] [&_input:focus]:outline-emerald-[450]"
      text="caret-emerald-[450]"
      bgColor="light" /><CaretSample
      class="caret-emerald-[550] outline-emerald-[550] [&_input:focus]:outline-emerald-[550]"
      text="caret-emerald-[550]"
      bgColor="light" /><CaretSample
      class="caret-emerald-[650] outline-emerald-[650] [&_input:focus]:outline-emerald-[650]"
      text="caret-emerald-[650]"
      bgColor="light" /><CaretSample
      class="caret-emerald-[750] outline-emerald-[750] [&_input:focus]:outline-emerald-[750]"
      text="caret-emerald-[750]"
      bgColor="light" /><CaretSample
      class="caret-emerald-[850] outline-emerald-[850] [&_input:focus]:outline-emerald-[850]"
      text="caret-emerald-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-fuchsia"
    ><CaretSample
      class="caret-fuchsia-[25] outline-fuchsia-[25] [&_input:focus]:outline-fuchsia-[25]"
      text="caret-fuchsia-[25]"
      bgColor="dark" /><CaretSample
      class="caret-fuchsia-[150] outline-fuchsia-[150] [&_input:focus]:outline-fuchsia-[150]"
      text="caret-fuchsia-[150]"
      bgColor="dark" /><CaretSample
      class="caret-fuchsia-[250] outline-fuchsia-[250] [&_input:focus]:outline-fuchsia-[250]"
      text="caret-fuchsia-[250]"
      bgColor="dark" /><CaretSample
      class="caret-fuchsia-[350] outline-fuchsia-[350] [&_input:focus]:outline-fuchsia-[350]"
      text="caret-fuchsia-[350]"
      bgColor="light" /><CaretSample
      class="caret-fuchsia-[450] outline-fuchsia-[450] [&_input:focus]:outline-fuchsia-[450]"
      text="caret-fuchsia-[450]"
      bgColor="light" /><CaretSample
      class="caret-fuchsia-[550] outline-fuchsia-[550] [&_input:focus]:outline-fuchsia-[550]"
      text="caret-fuchsia-[550]"
      bgColor="light" /><CaretSample
      class="caret-fuchsia-[650] outline-fuchsia-[650] [&_input:focus]:outline-fuchsia-[650]"
      text="caret-fuchsia-[650]"
      bgColor="light" /><CaretSample
      class="caret-fuchsia-[750] outline-fuchsia-[750] [&_input:focus]:outline-fuchsia-[750]"
      text="caret-fuchsia-[750]"
      bgColor="light" /><CaretSample
      class="caret-fuchsia-[850] outline-fuchsia-[850] [&_input:focus]:outline-fuchsia-[850]"
      text="caret-fuchsia-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-gray"
    ><CaretSample
      class="caret-gray-[25] outline-gray-[25] [&_input:focus]:outline-gray-[25]"
      text="caret-gray-[25]"
      bgColor="dark" /><CaretSample
      class="caret-gray-[150] outline-gray-[150] [&_input:focus]:outline-gray-[150]"
      text="caret-gray-[150]"
      bgColor="dark" /><CaretSample
      class="caret-gray-[250] outline-gray-[250] [&_input:focus]:outline-gray-[250]"
      text="caret-gray-[250]"
      bgColor="dark" /><CaretSample
      class="caret-gray-[350] outline-gray-[350] [&_input:focus]:outline-gray-[350]"
      text="caret-gray-[350]"
      bgColor="light" /><CaretSample
      class="caret-gray-[450] outline-gray-[450] [&_input:focus]:outline-gray-[450]"
      text="caret-gray-[450]"
      bgColor="light" /><CaretSample
      class="caret-gray-[550] outline-gray-[550] [&_input:focus]:outline-gray-[550]"
      text="caret-gray-[550]"
      bgColor="light" /><CaretSample
      class="caret-gray-[650] outline-gray-[650] [&_input:focus]:outline-gray-[650]"
      text="caret-gray-[650]"
      bgColor="light" /><CaretSample
      class="caret-gray-[750] outline-gray-[750] [&_input:focus]:outline-gray-[750]"
      text="caret-gray-[750]"
      bgColor="light" /><CaretSample
      class="caret-gray-[850] outline-gray-[850] [&_input:focus]:outline-gray-[850]"
      text="caret-gray-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-green"
    ><CaretSample
      class="caret-green-[25] outline-green-[25] [&_input:focus]:outline-green-[25]"
      text="caret-green-[25]"
      bgColor="dark" /><CaretSample
      class="caret-green-[150] outline-green-[150] [&_input:focus]:outline-green-[150]"
      text="caret-green-[150]"
      bgColor="dark" /><CaretSample
      class="caret-green-[250] outline-green-[250] [&_input:focus]:outline-green-[250]"
      text="caret-green-[250]"
      bgColor="dark" /><CaretSample
      class="caret-green-[350] outline-green-[350] [&_input:focus]:outline-green-[350]"
      text="caret-green-[350]"
      bgColor="dark" /><CaretSample
      class="caret-green-[450] outline-green-[450] [&_input:focus]:outline-green-[450]"
      text="caret-green-[450]"
      bgColor="light" /><CaretSample
      class="caret-green-[550] outline-green-[550] [&_input:focus]:outline-green-[550]"
      text="caret-green-[550]"
      bgColor="light" /><CaretSample
      class="caret-green-[650] outline-green-[650] [&_input:focus]:outline-green-[650]"
      text="caret-green-[650]"
      bgColor="light" /><CaretSample
      class="caret-green-[750] outline-green-[750] [&_input:focus]:outline-green-[750]"
      text="caret-green-[750]"
      bgColor="light" /><CaretSample
      class="caret-green-[850] outline-green-[850] [&_input:focus]:outline-green-[850]"
      text="caret-green-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-grey"
    ><CaretSample
      class="caret-grey-[25] outline-grey-[25] [&_input:focus]:outline-grey-[25]"
      text="caret-grey-[25]"
      bgColor="dark" /><CaretSample
      class="caret-grey-[150] outline-grey-[150] [&_input:focus]:outline-grey-[150]"
      text="caret-grey-[150]"
      bgColor="dark" /><CaretSample
      class="caret-grey-[250] outline-grey-[250] [&_input:focus]:outline-grey-[250]"
      text="caret-grey-[250]"
      bgColor="dark" /><CaretSample
      class="caret-grey-[350] outline-grey-[350] [&_input:focus]:outline-grey-[350]"
      text="caret-grey-[350]"
      bgColor="light" /><CaretSample
      class="caret-grey-[450] outline-grey-[450] [&_input:focus]:outline-grey-[450]"
      text="caret-grey-[450]"
      bgColor="light" /><CaretSample
      class="caret-grey-[550] outline-grey-[550] [&_input:focus]:outline-grey-[550]"
      text="caret-grey-[550]"
      bgColor="light" /><CaretSample
      class="caret-grey-[650] outline-grey-[650] [&_input:focus]:outline-grey-[650]"
      text="caret-grey-[650]"
      bgColor="light" /><CaretSample
      class="caret-grey-[750] outline-grey-[750] [&_input:focus]:outline-grey-[750]"
      text="caret-grey-[750]"
      bgColor="light" /><CaretSample
      class="caret-grey-[850] outline-grey-[850] [&_input:focus]:outline-grey-[850]"
      text="caret-grey-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-indigo"
    ><CaretSample
      class="caret-indigo-[25] outline-indigo-[25] [&_input:focus]:outline-indigo-[25]"
      text="caret-indigo-[25]"
      bgColor="dark" /><CaretSample
      class="caret-indigo-[150] outline-indigo-[150] [&_input:focus]:outline-indigo-[150]"
      text="caret-indigo-[150]"
      bgColor="dark" /><CaretSample
      class="caret-indigo-[250] outline-indigo-[250] [&_input:focus]:outline-indigo-[250]"
      text="caret-indigo-[250]"
      bgColor="light" /><CaretSample
      class="caret-indigo-[350] outline-indigo-[350] [&_input:focus]:outline-indigo-[350]"
      text="caret-indigo-[350]"
      bgColor="light" /><CaretSample
      class="caret-indigo-[450] outline-indigo-[450] [&_input:focus]:outline-indigo-[450]"
      text="caret-indigo-[450]"
      bgColor="light" /><CaretSample
      class="caret-indigo-[550] outline-indigo-[550] [&_input:focus]:outline-indigo-[550]"
      text="caret-indigo-[550]"
      bgColor="light" /><CaretSample
      class="caret-indigo-[650] outline-indigo-[650] [&_input:focus]:outline-indigo-[650]"
      text="caret-indigo-[650]"
      bgColor="light" /><CaretSample
      class="caret-indigo-[750] outline-indigo-[750] [&_input:focus]:outline-indigo-[750]"
      text="caret-indigo-[750]"
      bgColor="light" /><CaretSample
      class="caret-indigo-[850] outline-indigo-[850] [&_input:focus]:outline-indigo-[850]"
      text="caret-indigo-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-lime"
    ><CaretSample
      class="caret-lime-[25] outline-lime-[25] [&_input:focus]:outline-lime-[25]"
      text="caret-lime-[25]"
      bgColor="dark" /><CaretSample
      class="caret-lime-[150] outline-lime-[150] [&_input:focus]:outline-lime-[150]"
      text="caret-lime-[150]"
      bgColor="dark" /><CaretSample
      class="caret-lime-[250] outline-lime-[250] [&_input:focus]:outline-lime-[250]"
      text="caret-lime-[250]"
      bgColor="dark" /><CaretSample
      class="caret-lime-[350] outline-lime-[350] [&_input:focus]:outline-lime-[350]"
      text="caret-lime-[350]"
      bgColor="dark" /><CaretSample
      class="caret-lime-[450] outline-lime-[450] [&_input:focus]:outline-lime-[450]"
      text="caret-lime-[450]"
      bgColor="light" /><CaretSample
      class="caret-lime-[550] outline-lime-[550] [&_input:focus]:outline-lime-[550]"
      text="caret-lime-[550]"
      bgColor="light" /><CaretSample
      class="caret-lime-[650] outline-lime-[650] [&_input:focus]:outline-lime-[650]"
      text="caret-lime-[650]"
      bgColor="light" /><CaretSample
      class="caret-lime-[750] outline-lime-[750] [&_input:focus]:outline-lime-[750]"
      text="caret-lime-[750]"
      bgColor="light" /><CaretSample
      class="caret-lime-[850] outline-lime-[850] [&_input:focus]:outline-lime-[850]"
      text="caret-lime-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-neutral"
    ><CaretSample
      class="caret-neutral-[25] outline-neutral-[25] [&_input:focus]:outline-neutral-[25]"
      text="caret-neutral-[25]"
      bgColor="dark" /><CaretSample
      class="caret-neutral-[150] outline-neutral-[150] [&_input:focus]:outline-neutral-[150]"
      text="caret-neutral-[150]"
      bgColor="dark" /><CaretSample
      class="caret-neutral-[250] outline-neutral-[250] [&_input:focus]:outline-neutral-[250]"
      text="caret-neutral-[250]"
      bgColor="dark" /><CaretSample
      class="caret-neutral-[350] outline-neutral-[350] [&_input:focus]:outline-neutral-[350]"
      text="caret-neutral-[350]"
      bgColor="light" /><CaretSample
      class="caret-neutral-[450] outline-neutral-[450] [&_input:focus]:outline-neutral-[450]"
      text="caret-neutral-[450]"
      bgColor="light" /><CaretSample
      class="caret-neutral-[550] outline-neutral-[550] [&_input:focus]:outline-neutral-[550]"
      text="caret-neutral-[550]"
      bgColor="light" /><CaretSample
      class="caret-neutral-[650] outline-neutral-[650] [&_input:focus]:outline-neutral-[650]"
      text="caret-neutral-[650]"
      bgColor="light" /><CaretSample
      class="caret-neutral-[750] outline-neutral-[750] [&_input:focus]:outline-neutral-[750]"
      text="caret-neutral-[750]"
      bgColor="light" /><CaretSample
      class="caret-neutral-[850] outline-neutral-[850] [&_input:focus]:outline-neutral-[850]"
      text="caret-neutral-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-orange"
    ><CaretSample
      class="caret-orange-[25] outline-orange-[25] [&_input:focus]:outline-orange-[25]"
      text="caret-orange-[25]"
      bgColor="dark" /><CaretSample
      class="caret-orange-[150] outline-orange-[150] [&_input:focus]:outline-orange-[150]"
      text="caret-orange-[150]"
      bgColor="dark" /><CaretSample
      class="caret-orange-[250] outline-orange-[250] [&_input:focus]:outline-orange-[250]"
      text="caret-orange-[250]"
      bgColor="dark" /><CaretSample
      class="caret-orange-[350] outline-orange-[350] [&_input:focus]:outline-orange-[350]"
      text="caret-orange-[350]"
      bgColor="light" /><CaretSample
      class="caret-orange-[450] outline-orange-[450] [&_input:focus]:outline-orange-[450]"
      text="caret-orange-[450]"
      bgColor="light" /><CaretSample
      class="caret-orange-[550] outline-orange-[550] [&_input:focus]:outline-orange-[550]"
      text="caret-orange-[550]"
      bgColor="light" /><CaretSample
      class="caret-orange-[650] outline-orange-[650] [&_input:focus]:outline-orange-[650]"
      text="caret-orange-[650]"
      bgColor="light" /><CaretSample
      class="caret-orange-[750] outline-orange-[750] [&_input:focus]:outline-orange-[750]"
      text="caret-orange-[750]"
      bgColor="light" /><CaretSample
      class="caret-orange-[850] outline-orange-[850] [&_input:focus]:outline-orange-[850]"
      text="caret-orange-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-pink"
    ><CaretSample
      class="caret-pink-[25] outline-pink-[25] [&_input:focus]:outline-pink-[25]"
      text="caret-pink-[25]"
      bgColor="dark" /><CaretSample
      class="caret-pink-[150] outline-pink-[150] [&_input:focus]:outline-pink-[150]"
      text="caret-pink-[150]"
      bgColor="dark" /><CaretSample
      class="caret-pink-[250] outline-pink-[250] [&_input:focus]:outline-pink-[250]"
      text="caret-pink-[250]"
      bgColor="light" /><CaretSample
      class="caret-pink-[350] outline-pink-[350] [&_input:focus]:outline-pink-[350]"
      text="caret-pink-[350]"
      bgColor="light" /><CaretSample
      class="caret-pink-[450] outline-pink-[450] [&_input:focus]:outline-pink-[450]"
      text="caret-pink-[450]"
      bgColor="light" /><CaretSample
      class="caret-pink-[550] outline-pink-[550] [&_input:focus]:outline-pink-[550]"
      text="caret-pink-[550]"
      bgColor="light" /><CaretSample
      class="caret-pink-[650] outline-pink-[650] [&_input:focus]:outline-pink-[650]"
      text="caret-pink-[650]"
      bgColor="light" /><CaretSample
      class="caret-pink-[750] outline-pink-[750] [&_input:focus]:outline-pink-[750]"
      text="caret-pink-[750]"
      bgColor="light" /><CaretSample
      class="caret-pink-[850] outline-pink-[850] [&_input:focus]:outline-pink-[850]"
      text="caret-pink-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-purple"
    ><CaretSample
      class="caret-purple-[25] outline-purple-[25] [&_input:focus]:outline-purple-[25]"
      text="caret-purple-[25]"
      bgColor="dark" /><CaretSample
      class="caret-purple-[150] outline-purple-[150] [&_input:focus]:outline-purple-[150]"
      text="caret-purple-[150]"
      bgColor="dark" /><CaretSample
      class="caret-purple-[250] outline-purple-[250] [&_input:focus]:outline-purple-[250]"
      text="caret-purple-[250]"
      bgColor="dark" /><CaretSample
      class="caret-purple-[350] outline-purple-[350] [&_input:focus]:outline-purple-[350]"
      text="caret-purple-[350]"
      bgColor="light" /><CaretSample
      class="caret-purple-[450] outline-purple-[450] [&_input:focus]:outline-purple-[450]"
      text="caret-purple-[450]"
      bgColor="light" /><CaretSample
      class="caret-purple-[550] outline-purple-[550] [&_input:focus]:outline-purple-[550]"
      text="caret-purple-[550]"
      bgColor="light" /><CaretSample
      class="caret-purple-[650] outline-purple-[650] [&_input:focus]:outline-purple-[650]"
      text="caret-purple-[650]"
      bgColor="light" /><CaretSample
      class="caret-purple-[750] outline-purple-[750] [&_input:focus]:outline-purple-[750]"
      text="caret-purple-[750]"
      bgColor="light" /><CaretSample
      class="caret-purple-[850] outline-purple-[850] [&_input:focus]:outline-purple-[850]"
      text="caret-purple-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-red"
    ><CaretSample
      class="caret-red-[25] outline-red-[25] [&_input:focus]:outline-red-[25]"
      text="caret-red-[25]"
      bgColor="dark" /><CaretSample
      class="caret-red-[150] outline-red-[150] [&_input:focus]:outline-red-[150]"
      text="caret-red-[150]"
      bgColor="dark" /><CaretSample
      class="caret-red-[250] outline-red-[250] [&_input:focus]:outline-red-[250]"
      text="caret-red-[250]"
      bgColor="light" /><CaretSample
      class="caret-red-[350] outline-red-[350] [&_input:focus]:outline-red-[350]"
      text="caret-red-[350]"
      bgColor="light" /><CaretSample
      class="caret-red-[450] outline-red-[450] [&_input:focus]:outline-red-[450]"
      text="caret-red-[450]"
      bgColor="light" /><CaretSample
      class="caret-red-[550] outline-red-[550] [&_input:focus]:outline-red-[550]"
      text="caret-red-[550]"
      bgColor="light" /><CaretSample
      class="caret-red-[650] outline-red-[650] [&_input:focus]:outline-red-[650]"
      text="caret-red-[650]"
      bgColor="light" /><CaretSample
      class="caret-red-[750] outline-red-[750] [&_input:focus]:outline-red-[750]"
      text="caret-red-[750]"
      bgColor="light" /><CaretSample
      class="caret-red-[850] outline-red-[850] [&_input:focus]:outline-red-[850]"
      text="caret-red-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-rose"
    ><CaretSample
      class="caret-rose-[25] outline-rose-[25] [&_input:focus]:outline-rose-[25]"
      text="caret-rose-[25]"
      bgColor="dark" /><CaretSample
      class="caret-rose-[150] outline-rose-[150] [&_input:focus]:outline-rose-[150]"
      text="caret-rose-[150]"
      bgColor="dark" /><CaretSample
      class="caret-rose-[250] outline-rose-[250] [&_input:focus]:outline-rose-[250]"
      text="caret-rose-[250]"
      bgColor="light" /><CaretSample
      class="caret-rose-[350] outline-rose-[350] [&_input:focus]:outline-rose-[350]"
      text="caret-rose-[350]"
      bgColor="light" /><CaretSample
      class="caret-rose-[450] outline-rose-[450] [&_input:focus]:outline-rose-[450]"
      text="caret-rose-[450]"
      bgColor="light" /><CaretSample
      class="caret-rose-[550] outline-rose-[550] [&_input:focus]:outline-rose-[550]"
      text="caret-rose-[550]"
      bgColor="light" /><CaretSample
      class="caret-rose-[650] outline-rose-[650] [&_input:focus]:outline-rose-[650]"
      text="caret-rose-[650]"
      bgColor="light" /><CaretSample
      class="caret-rose-[750] outline-rose-[750] [&_input:focus]:outline-rose-[750]"
      text="caret-rose-[750]"
      bgColor="light" /><CaretSample
      class="caret-rose-[850] outline-rose-[850] [&_input:focus]:outline-rose-[850]"
      text="caret-rose-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-sky"
    ><CaretSample
      class="caret-sky-[25] outline-sky-[25] [&_input:focus]:outline-sky-[25]"
      text="caret-sky-[25]"
      bgColor="dark" /><CaretSample
      class="caret-sky-[150] outline-sky-[150] [&_input:focus]:outline-sky-[150]"
      text="caret-sky-[150]"
      bgColor="dark" /><CaretSample
      class="caret-sky-[250] outline-sky-[250] [&_input:focus]:outline-sky-[250]"
      text="caret-sky-[250]"
      bgColor="dark" /><CaretSample
      class="caret-sky-[350] outline-sky-[350] [&_input:focus]:outline-sky-[350]"
      text="caret-sky-[350]"
      bgColor="light" /><CaretSample
      class="caret-sky-[450] outline-sky-[450] [&_input:focus]:outline-sky-[450]"
      text="caret-sky-[450]"
      bgColor="light" /><CaretSample
      class="caret-sky-[550] outline-sky-[550] [&_input:focus]:outline-sky-[550]"
      text="caret-sky-[550]"
      bgColor="light" /><CaretSample
      class="caret-sky-[650] outline-sky-[650] [&_input:focus]:outline-sky-[650]"
      text="caret-sky-[650]"
      bgColor="light" /><CaretSample
      class="caret-sky-[750] outline-sky-[750] [&_input:focus]:outline-sky-[750]"
      text="caret-sky-[750]"
      bgColor="light" /><CaretSample
      class="caret-sky-[850] outline-sky-[850] [&_input:focus]:outline-sky-[850]"
      text="caret-sky-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-slate"
    ><CaretSample
      class="caret-slate-[25] outline-slate-[25] [&_input:focus]:outline-slate-[25]"
      text="caret-slate-[25]"
      bgColor="dark" /><CaretSample
      class="caret-slate-[150] outline-slate-[150] [&_input:focus]:outline-slate-[150]"
      text="caret-slate-[150]"
      bgColor="dark" /><CaretSample
      class="caret-slate-[250] outline-slate-[250] [&_input:focus]:outline-slate-[250]"
      text="caret-slate-[250]"
      bgColor="dark" /><CaretSample
      class="caret-slate-[350] outline-slate-[350] [&_input:focus]:outline-slate-[350]"
      text="caret-slate-[350]"
      bgColor="light" /><CaretSample
      class="caret-slate-[450] outline-slate-[450] [&_input:focus]:outline-slate-[450]"
      text="caret-slate-[450]"
      bgColor="light" /><CaretSample
      class="caret-slate-[550] outline-slate-[550] [&_input:focus]:outline-slate-[550]"
      text="caret-slate-[550]"
      bgColor="light" /><CaretSample
      class="caret-slate-[650] outline-slate-[650] [&_input:focus]:outline-slate-[650]"
      text="caret-slate-[650]"
      bgColor="light" /><CaretSample
      class="caret-slate-[750] outline-slate-[750] [&_input:focus]:outline-slate-[750]"
      text="caret-slate-[750]"
      bgColor="light" /><CaretSample
      class="caret-slate-[850] outline-slate-[850] [&_input:focus]:outline-slate-[850]"
      text="caret-slate-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-stone"
    ><CaretSample
      class="caret-stone-[25] outline-stone-[25] [&_input:focus]:outline-stone-[25]"
      text="caret-stone-[25]"
      bgColor="dark" /><CaretSample
      class="caret-stone-[150] outline-stone-[150] [&_input:focus]:outline-stone-[150]"
      text="caret-stone-[150]"
      bgColor="dark" /><CaretSample
      class="caret-stone-[250] outline-stone-[250] [&_input:focus]:outline-stone-[250]"
      text="caret-stone-[250]"
      bgColor="dark" /><CaretSample
      class="caret-stone-[350] outline-stone-[350] [&_input:focus]:outline-stone-[350]"
      text="caret-stone-[350]"
      bgColor="light" /><CaretSample
      class="caret-stone-[450] outline-stone-[450] [&_input:focus]:outline-stone-[450]"
      text="caret-stone-[450]"
      bgColor="light" /><CaretSample
      class="caret-stone-[550] outline-stone-[550] [&_input:focus]:outline-stone-[550]"
      text="caret-stone-[550]"
      bgColor="light" /><CaretSample
      class="caret-stone-[650] outline-stone-[650] [&_input:focus]:outline-stone-[650]"
      text="caret-stone-[650]"
      bgColor="light" /><CaretSample
      class="caret-stone-[750] outline-stone-[750] [&_input:focus]:outline-stone-[750]"
      text="caret-stone-[750]"
      bgColor="light" /><CaretSample
      class="caret-stone-[850] outline-stone-[850] [&_input:focus]:outline-stone-[850]"
      text="caret-stone-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-teal"
    ><CaretSample
      class="caret-teal-[25] outline-teal-[25] [&_input:focus]:outline-teal-[25]"
      text="caret-teal-[25]"
      bgColor="dark" /><CaretSample
      class="caret-teal-[150] outline-teal-[150] [&_input:focus]:outline-teal-[150]"
      text="caret-teal-[150]"
      bgColor="dark" /><CaretSample
      class="caret-teal-[250] outline-teal-[250] [&_input:focus]:outline-teal-[250]"
      text="caret-teal-[250]"
      bgColor="dark" /><CaretSample
      class="caret-teal-[350] outline-teal-[350] [&_input:focus]:outline-teal-[350]"
      text="caret-teal-[350]"
      bgColor="light" /><CaretSample
      class="caret-teal-[450] outline-teal-[450] [&_input:focus]:outline-teal-[450]"
      text="caret-teal-[450]"
      bgColor="light" /><CaretSample
      class="caret-teal-[550] outline-teal-[550] [&_input:focus]:outline-teal-[550]"
      text="caret-teal-[550]"
      bgColor="light" /><CaretSample
      class="caret-teal-[650] outline-teal-[650] [&_input:focus]:outline-teal-[650]"
      text="caret-teal-[650]"
      bgColor="light" /><CaretSample
      class="caret-teal-[750] outline-teal-[750] [&_input:focus]:outline-teal-[750]"
      text="caret-teal-[750]"
      bgColor="light" /><CaretSample
      class="caret-teal-[850] outline-teal-[850] [&_input:focus]:outline-teal-[850]"
      text="caret-teal-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-violet"
    ><CaretSample
      class="caret-violet-[25] outline-violet-[25] [&_input:focus]:outline-violet-[25]"
      text="caret-violet-[25]"
      bgColor="dark" /><CaretSample
      class="caret-violet-[150] outline-violet-[150] [&_input:focus]:outline-violet-[150]"
      text="caret-violet-[150]"
      bgColor="dark" /><CaretSample
      class="caret-violet-[250] outline-violet-[250] [&_input:focus]:outline-violet-[250]"
      text="caret-violet-[250]"
      bgColor="light" /><CaretSample
      class="caret-violet-[350] outline-violet-[350] [&_input:focus]:outline-violet-[350]"
      text="caret-violet-[350]"
      bgColor="light" /><CaretSample
      class="caret-violet-[450] outline-violet-[450] [&_input:focus]:outline-violet-[450]"
      text="caret-violet-[450]"
      bgColor="light" /><CaretSample
      class="caret-violet-[550] outline-violet-[550] [&_input:focus]:outline-violet-[550]"
      text="caret-violet-[550]"
      bgColor="light" /><CaretSample
      class="caret-violet-[650] outline-violet-[650] [&_input:focus]:outline-violet-[650]"
      text="caret-violet-[650]"
      bgColor="light" /><CaretSample
      class="caret-violet-[750] outline-violet-[750] [&_input:focus]:outline-violet-[750]"
      text="caret-violet-[750]"
      bgColor="light" /><CaretSample
      class="caret-violet-[850] outline-violet-[850] [&_input:focus]:outline-violet-[850]"
      text="caret-violet-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-yellow"
    ><CaretSample
      class="caret-yellow-[25] outline-yellow-[25] [&_input:focus]:outline-yellow-[25]"
      text="caret-yellow-[25]"
      bgColor="dark" /><CaretSample
      class="caret-yellow-[150] outline-yellow-[150] [&_input:focus]:outline-yellow-[150]"
      text="caret-yellow-[150]"
      bgColor="dark" /><CaretSample
      class="caret-yellow-[250] outline-yellow-[250] [&_input:focus]:outline-yellow-[250]"
      text="caret-yellow-[250]"
      bgColor="dark" /><CaretSample
      class="caret-yellow-[350] outline-yellow-[350] [&_input:focus]:outline-yellow-[350]"
      text="caret-yellow-[350]"
      bgColor="dark" /><CaretSample
      class="caret-yellow-[450] outline-yellow-[450] [&_input:focus]:outline-yellow-[450]"
      text="caret-yellow-[450]"
      bgColor="light" /><CaretSample
      class="caret-yellow-[550] outline-yellow-[550] [&_input:focus]:outline-yellow-[550]"
      text="caret-yellow-[550]"
      bgColor="light" /><CaretSample
      class="caret-yellow-[650] outline-yellow-[650] [&_input:focus]:outline-yellow-[650]"
      text="caret-yellow-[650]"
      bgColor="light" /><CaretSample
      class="caret-yellow-[750] outline-yellow-[750] [&_input:focus]:outline-yellow-[750]"
      text="caret-yellow-[750]"
      bgColor="light" /><CaretSample
      class="caret-yellow-[850] outline-yellow-[850] [&_input:focus]:outline-yellow-[850]"
      text="caret-yellow-[850]"
      bgColor="light"
  /></SampleRow>
  <SampleRow title="caret-zinc"
    ><CaretSample
      class="caret-zinc-[25] outline-zinc-[25] [&_input:focus]:outline-zinc-[25]"
      text="caret-zinc-[25]"
      bgColor="dark" /><CaretSample
      class="caret-zinc-[150] outline-zinc-[150] [&_input:focus]:outline-zinc-[150]"
      text="caret-zinc-[150]"
      bgColor="dark" /><CaretSample
      class="caret-zinc-[250] outline-zinc-[250] [&_input:focus]:outline-zinc-[250]"
      text="caret-zinc-[250]"
      bgColor="dark" /><CaretSample
      class="caret-zinc-[350] outline-zinc-[350] [&_input:focus]:outline-zinc-[350]"
      text="caret-zinc-[350]"
      bgColor="light" /><CaretSample
      class="caret-zinc-[450] outline-zinc-[450] [&_input:focus]:outline-zinc-[450]"
      text="caret-zinc-[450]"
      bgColor="light" /><CaretSample
      class="caret-zinc-[550] outline-zinc-[550] [&_input:focus]:outline-zinc-[550]"
      text="caret-zinc-[550]"
      bgColor="light" /><CaretSample
      class="caret-zinc-[650] outline-zinc-[650] [&_input:focus]:outline-zinc-[650]"
      text="caret-zinc-[650]"
      bgColor="light" /><CaretSample
      class="caret-zinc-[750] outline-zinc-[750] [&_input:focus]:outline-zinc-[750]"
      text="caret-zinc-[750]"
      bgColor="light" /><CaretSample
      class="caret-zinc-[850] outline-zinc-[850] [&_input:focus]:outline-zinc-[850]"
      text="caret-zinc-[850]"
      bgColor="light"
  /></SampleRow>
</template>
