<template>
  <SampleRow title="bg-amber"
    ><BackgroundSample
      class="bg-amber-[25]"
      text="bg-amber-[25]"
      textColor="dark" /><BackgroundSample
      class="bg-amber-[150]"
      text="bg-amber-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-amber-[250]"
      text="bg-amber-[250]"
      textColor="dark" /><BackgroundSample
      class="bg-amber-[350]"
      text="bg-amber-[350]"
      textColor="dark" /><BackgroundSample
      class="bg-amber-[450]"
      text="bg-amber-[450]"
      textColor="light" /><BackgroundSample
      class="bg-amber-[550]"
      text="bg-amber-[550]"
      textColor="light" /><BackgroundSample
      class="bg-amber-[650]"
      text="bg-amber-[650]"
      textColor="light" /><BackgroundSample
      class="bg-amber-[750]"
      text="bg-amber-[750]"
      textColor="light" /><BackgroundSample
      class="bg-amber-[850]"
      text="bg-amber-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-blue"
    ><BackgroundSample class="bg-blue-[25]" text="bg-blue-[25]" textColor="dark" /><BackgroundSample
      class="bg-blue-[150]"
      text="bg-blue-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-blue-[250]"
      text="bg-blue-[250]"
      textColor="light" /><BackgroundSample
      class="bg-blue-[350]"
      text="bg-blue-[350]"
      textColor="light" /><BackgroundSample
      class="bg-blue-[450]"
      text="bg-blue-[450]"
      textColor="light" /><BackgroundSample
      class="bg-blue-[550]"
      text="bg-blue-[550]"
      textColor="light" /><BackgroundSample
      class="bg-blue-[650]"
      text="bg-blue-[650]"
      textColor="light" /><BackgroundSample
      class="bg-blue-[750]"
      text="bg-blue-[750]"
      textColor="light" /><BackgroundSample
      class="bg-blue-[850]"
      text="bg-blue-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-cyan"
    ><BackgroundSample class="bg-cyan-[25]" text="bg-cyan-[25]" textColor="dark" /><BackgroundSample
      class="bg-cyan-[150]"
      text="bg-cyan-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-cyan-[250]"
      text="bg-cyan-[250]"
      textColor="dark" /><BackgroundSample
      class="bg-cyan-[350]"
      text="bg-cyan-[350]"
      textColor="light" /><BackgroundSample
      class="bg-cyan-[450]"
      text="bg-cyan-[450]"
      textColor="light" /><BackgroundSample
      class="bg-cyan-[550]"
      text="bg-cyan-[550]"
      textColor="light" /><BackgroundSample
      class="bg-cyan-[650]"
      text="bg-cyan-[650]"
      textColor="light" /><BackgroundSample
      class="bg-cyan-[750]"
      text="bg-cyan-[750]"
      textColor="light" /><BackgroundSample
      class="bg-cyan-[850]"
      text="bg-cyan-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-emerald"
    ><BackgroundSample
      class="bg-emerald-[25]"
      text="bg-emerald-[25]"
      textColor="dark" /><BackgroundSample
      class="bg-emerald-[150]"
      text="bg-emerald-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-emerald-[250]"
      text="bg-emerald-[250]"
      textColor="dark" /><BackgroundSample
      class="bg-emerald-[350]"
      text="bg-emerald-[350]"
      textColor="light" /><BackgroundSample
      class="bg-emerald-[450]"
      text="bg-emerald-[450]"
      textColor="light" /><BackgroundSample
      class="bg-emerald-[550]"
      text="bg-emerald-[550]"
      textColor="light" /><BackgroundSample
      class="bg-emerald-[650]"
      text="bg-emerald-[650]"
      textColor="light" /><BackgroundSample
      class="bg-emerald-[750]"
      text="bg-emerald-[750]"
      textColor="light" /><BackgroundSample
      class="bg-emerald-[850]"
      text="bg-emerald-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-fuchsia"
    ><BackgroundSample
      class="bg-fuchsia-[25]"
      text="bg-fuchsia-[25]"
      textColor="dark" /><BackgroundSample
      class="bg-fuchsia-[150]"
      text="bg-fuchsia-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-fuchsia-[250]"
      text="bg-fuchsia-[250]"
      textColor="dark" /><BackgroundSample
      class="bg-fuchsia-[350]"
      text="bg-fuchsia-[350]"
      textColor="light" /><BackgroundSample
      class="bg-fuchsia-[450]"
      text="bg-fuchsia-[450]"
      textColor="light" /><BackgroundSample
      class="bg-fuchsia-[550]"
      text="bg-fuchsia-[550]"
      textColor="light" /><BackgroundSample
      class="bg-fuchsia-[650]"
      text="bg-fuchsia-[650]"
      textColor="light" /><BackgroundSample
      class="bg-fuchsia-[750]"
      text="bg-fuchsia-[750]"
      textColor="light" /><BackgroundSample
      class="bg-fuchsia-[850]"
      text="bg-fuchsia-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-gray"
    ><BackgroundSample class="bg-gray-[25]" text="bg-gray-[25]" textColor="dark" /><BackgroundSample
      class="bg-gray-[150]"
      text="bg-gray-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-gray-[250]"
      text="bg-gray-[250]"
      textColor="dark" /><BackgroundSample
      class="bg-gray-[350]"
      text="bg-gray-[350]"
      textColor="light" /><BackgroundSample
      class="bg-gray-[450]"
      text="bg-gray-[450]"
      textColor="light" /><BackgroundSample
      class="bg-gray-[550]"
      text="bg-gray-[550]"
      textColor="light" /><BackgroundSample
      class="bg-gray-[650]"
      text="bg-gray-[650]"
      textColor="light" /><BackgroundSample
      class="bg-gray-[750]"
      text="bg-gray-[750]"
      textColor="light" /><BackgroundSample
      class="bg-gray-[850]"
      text="bg-gray-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-green"
    ><BackgroundSample
      class="bg-green-[25]"
      text="bg-green-[25]"
      textColor="dark" /><BackgroundSample
      class="bg-green-[150]"
      text="bg-green-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-green-[250]"
      text="bg-green-[250]"
      textColor="dark" /><BackgroundSample
      class="bg-green-[350]"
      text="bg-green-[350]"
      textColor="dark" /><BackgroundSample
      class="bg-green-[450]"
      text="bg-green-[450]"
      textColor="light" /><BackgroundSample
      class="bg-green-[550]"
      text="bg-green-[550]"
      textColor="light" /><BackgroundSample
      class="bg-green-[650]"
      text="bg-green-[650]"
      textColor="light" /><BackgroundSample
      class="bg-green-[750]"
      text="bg-green-[750]"
      textColor="light" /><BackgroundSample
      class="bg-green-[850]"
      text="bg-green-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-grey"
    ><BackgroundSample class="bg-grey-[25]" text="bg-grey-[25]" textColor="dark" /><BackgroundSample
      class="bg-grey-[150]"
      text="bg-grey-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-grey-[250]"
      text="bg-grey-[250]"
      textColor="dark" /><BackgroundSample
      class="bg-grey-[350]"
      text="bg-grey-[350]"
      textColor="light" /><BackgroundSample
      class="bg-grey-[450]"
      text="bg-grey-[450]"
      textColor="light" /><BackgroundSample
      class="bg-grey-[550]"
      text="bg-grey-[550]"
      textColor="light" /><BackgroundSample
      class="bg-grey-[650]"
      text="bg-grey-[650]"
      textColor="light" /><BackgroundSample
      class="bg-grey-[750]"
      text="bg-grey-[750]"
      textColor="light" /><BackgroundSample
      class="bg-grey-[850]"
      text="bg-grey-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-indigo"
    ><BackgroundSample
      class="bg-indigo-[25]"
      text="bg-indigo-[25]"
      textColor="dark" /><BackgroundSample
      class="bg-indigo-[150]"
      text="bg-indigo-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-indigo-[250]"
      text="bg-indigo-[250]"
      textColor="light" /><BackgroundSample
      class="bg-indigo-[350]"
      text="bg-indigo-[350]"
      textColor="light" /><BackgroundSample
      class="bg-indigo-[450]"
      text="bg-indigo-[450]"
      textColor="light" /><BackgroundSample
      class="bg-indigo-[550]"
      text="bg-indigo-[550]"
      textColor="light" /><BackgroundSample
      class="bg-indigo-[650]"
      text="bg-indigo-[650]"
      textColor="light" /><BackgroundSample
      class="bg-indigo-[750]"
      text="bg-indigo-[750]"
      textColor="light" /><BackgroundSample
      class="bg-indigo-[850]"
      text="bg-indigo-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-lime"
    ><BackgroundSample class="bg-lime-[25]" text="bg-lime-[25]" textColor="dark" /><BackgroundSample
      class="bg-lime-[150]"
      text="bg-lime-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-lime-[250]"
      text="bg-lime-[250]"
      textColor="dark" /><BackgroundSample
      class="bg-lime-[350]"
      text="bg-lime-[350]"
      textColor="dark" /><BackgroundSample
      class="bg-lime-[450]"
      text="bg-lime-[450]"
      textColor="light" /><BackgroundSample
      class="bg-lime-[550]"
      text="bg-lime-[550]"
      textColor="light" /><BackgroundSample
      class="bg-lime-[650]"
      text="bg-lime-[650]"
      textColor="light" /><BackgroundSample
      class="bg-lime-[750]"
      text="bg-lime-[750]"
      textColor="light" /><BackgroundSample
      class="bg-lime-[850]"
      text="bg-lime-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-neutral"
    ><BackgroundSample
      class="bg-neutral-[25]"
      text="bg-neutral-[25]"
      textColor="dark" /><BackgroundSample
      class="bg-neutral-[150]"
      text="bg-neutral-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-neutral-[250]"
      text="bg-neutral-[250]"
      textColor="dark" /><BackgroundSample
      class="bg-neutral-[350]"
      text="bg-neutral-[350]"
      textColor="light" /><BackgroundSample
      class="bg-neutral-[450]"
      text="bg-neutral-[450]"
      textColor="light" /><BackgroundSample
      class="bg-neutral-[550]"
      text="bg-neutral-[550]"
      textColor="light" /><BackgroundSample
      class="bg-neutral-[650]"
      text="bg-neutral-[650]"
      textColor="light" /><BackgroundSample
      class="bg-neutral-[750]"
      text="bg-neutral-[750]"
      textColor="light" /><BackgroundSample
      class="bg-neutral-[850]"
      text="bg-neutral-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-orange"
    ><BackgroundSample
      class="bg-orange-[25]"
      text="bg-orange-[25]"
      textColor="dark" /><BackgroundSample
      class="bg-orange-[150]"
      text="bg-orange-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-orange-[250]"
      text="bg-orange-[250]"
      textColor="dark" /><BackgroundSample
      class="bg-orange-[350]"
      text="bg-orange-[350]"
      textColor="light" /><BackgroundSample
      class="bg-orange-[450]"
      text="bg-orange-[450]"
      textColor="light" /><BackgroundSample
      class="bg-orange-[550]"
      text="bg-orange-[550]"
      textColor="light" /><BackgroundSample
      class="bg-orange-[650]"
      text="bg-orange-[650]"
      textColor="light" /><BackgroundSample
      class="bg-orange-[750]"
      text="bg-orange-[750]"
      textColor="light" /><BackgroundSample
      class="bg-orange-[850]"
      text="bg-orange-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-pink"
    ><BackgroundSample class="bg-pink-[25]" text="bg-pink-[25]" textColor="dark" /><BackgroundSample
      class="bg-pink-[150]"
      text="bg-pink-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-pink-[250]"
      text="bg-pink-[250]"
      textColor="light" /><BackgroundSample
      class="bg-pink-[350]"
      text="bg-pink-[350]"
      textColor="light" /><BackgroundSample
      class="bg-pink-[450]"
      text="bg-pink-[450]"
      textColor="light" /><BackgroundSample
      class="bg-pink-[550]"
      text="bg-pink-[550]"
      textColor="light" /><BackgroundSample
      class="bg-pink-[650]"
      text="bg-pink-[650]"
      textColor="light" /><BackgroundSample
      class="bg-pink-[750]"
      text="bg-pink-[750]"
      textColor="light" /><BackgroundSample
      class="bg-pink-[850]"
      text="bg-pink-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-purple"
    ><BackgroundSample
      class="bg-purple-[25]"
      text="bg-purple-[25]"
      textColor="dark" /><BackgroundSample
      class="bg-purple-[150]"
      text="bg-purple-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-purple-[250]"
      text="bg-purple-[250]"
      textColor="dark" /><BackgroundSample
      class="bg-purple-[350]"
      text="bg-purple-[350]"
      textColor="light" /><BackgroundSample
      class="bg-purple-[450]"
      text="bg-purple-[450]"
      textColor="light" /><BackgroundSample
      class="bg-purple-[550]"
      text="bg-purple-[550]"
      textColor="light" /><BackgroundSample
      class="bg-purple-[650]"
      text="bg-purple-[650]"
      textColor="light" /><BackgroundSample
      class="bg-purple-[750]"
      text="bg-purple-[750]"
      textColor="light" /><BackgroundSample
      class="bg-purple-[850]"
      text="bg-purple-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-red"
    ><BackgroundSample class="bg-red-[25]" text="bg-red-[25]" textColor="dark" /><BackgroundSample
      class="bg-red-[150]"
      text="bg-red-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-red-[250]"
      text="bg-red-[250]"
      textColor="light" /><BackgroundSample
      class="bg-red-[350]"
      text="bg-red-[350]"
      textColor="light" /><BackgroundSample
      class="bg-red-[450]"
      text="bg-red-[450]"
      textColor="light" /><BackgroundSample
      class="bg-red-[550]"
      text="bg-red-[550]"
      textColor="light" /><BackgroundSample
      class="bg-red-[650]"
      text="bg-red-[650]"
      textColor="light" /><BackgroundSample
      class="bg-red-[750]"
      text="bg-red-[750]"
      textColor="light" /><BackgroundSample
      class="bg-red-[850]"
      text="bg-red-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-rose"
    ><BackgroundSample class="bg-rose-[25]" text="bg-rose-[25]" textColor="dark" /><BackgroundSample
      class="bg-rose-[150]"
      text="bg-rose-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-rose-[250]"
      text="bg-rose-[250]"
      textColor="light" /><BackgroundSample
      class="bg-rose-[350]"
      text="bg-rose-[350]"
      textColor="light" /><BackgroundSample
      class="bg-rose-[450]"
      text="bg-rose-[450]"
      textColor="light" /><BackgroundSample
      class="bg-rose-[550]"
      text="bg-rose-[550]"
      textColor="light" /><BackgroundSample
      class="bg-rose-[650]"
      text="bg-rose-[650]"
      textColor="light" /><BackgroundSample
      class="bg-rose-[750]"
      text="bg-rose-[750]"
      textColor="light" /><BackgroundSample
      class="bg-rose-[850]"
      text="bg-rose-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-sky"
    ><BackgroundSample class="bg-sky-[25]" text="bg-sky-[25]" textColor="dark" /><BackgroundSample
      class="bg-sky-[150]"
      text="bg-sky-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-sky-[250]"
      text="bg-sky-[250]"
      textColor="dark" /><BackgroundSample
      class="bg-sky-[350]"
      text="bg-sky-[350]"
      textColor="light" /><BackgroundSample
      class="bg-sky-[450]"
      text="bg-sky-[450]"
      textColor="light" /><BackgroundSample
      class="bg-sky-[550]"
      text="bg-sky-[550]"
      textColor="light" /><BackgroundSample
      class="bg-sky-[650]"
      text="bg-sky-[650]"
      textColor="light" /><BackgroundSample
      class="bg-sky-[750]"
      text="bg-sky-[750]"
      textColor="light" /><BackgroundSample
      class="bg-sky-[850]"
      text="bg-sky-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-slate"
    ><BackgroundSample
      class="bg-slate-[25]"
      text="bg-slate-[25]"
      textColor="dark" /><BackgroundSample
      class="bg-slate-[150]"
      text="bg-slate-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-slate-[250]"
      text="bg-slate-[250]"
      textColor="dark" /><BackgroundSample
      class="bg-slate-[350]"
      text="bg-slate-[350]"
      textColor="light" /><BackgroundSample
      class="bg-slate-[450]"
      text="bg-slate-[450]"
      textColor="light" /><BackgroundSample
      class="bg-slate-[550]"
      text="bg-slate-[550]"
      textColor="light" /><BackgroundSample
      class="bg-slate-[650]"
      text="bg-slate-[650]"
      textColor="light" /><BackgroundSample
      class="bg-slate-[750]"
      text="bg-slate-[750]"
      textColor="light" /><BackgroundSample
      class="bg-slate-[850]"
      text="bg-slate-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-stone"
    ><BackgroundSample
      class="bg-stone-[25]"
      text="bg-stone-[25]"
      textColor="dark" /><BackgroundSample
      class="bg-stone-[150]"
      text="bg-stone-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-stone-[250]"
      text="bg-stone-[250]"
      textColor="dark" /><BackgroundSample
      class="bg-stone-[350]"
      text="bg-stone-[350]"
      textColor="light" /><BackgroundSample
      class="bg-stone-[450]"
      text="bg-stone-[450]"
      textColor="light" /><BackgroundSample
      class="bg-stone-[550]"
      text="bg-stone-[550]"
      textColor="light" /><BackgroundSample
      class="bg-stone-[650]"
      text="bg-stone-[650]"
      textColor="light" /><BackgroundSample
      class="bg-stone-[750]"
      text="bg-stone-[750]"
      textColor="light" /><BackgroundSample
      class="bg-stone-[850]"
      text="bg-stone-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-teal"
    ><BackgroundSample class="bg-teal-[25]" text="bg-teal-[25]" textColor="dark" /><BackgroundSample
      class="bg-teal-[150]"
      text="bg-teal-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-teal-[250]"
      text="bg-teal-[250]"
      textColor="dark" /><BackgroundSample
      class="bg-teal-[350]"
      text="bg-teal-[350]"
      textColor="light" /><BackgroundSample
      class="bg-teal-[450]"
      text="bg-teal-[450]"
      textColor="light" /><BackgroundSample
      class="bg-teal-[550]"
      text="bg-teal-[550]"
      textColor="light" /><BackgroundSample
      class="bg-teal-[650]"
      text="bg-teal-[650]"
      textColor="light" /><BackgroundSample
      class="bg-teal-[750]"
      text="bg-teal-[750]"
      textColor="light" /><BackgroundSample
      class="bg-teal-[850]"
      text="bg-teal-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-violet"
    ><BackgroundSample
      class="bg-violet-[25]"
      text="bg-violet-[25]"
      textColor="dark" /><BackgroundSample
      class="bg-violet-[150]"
      text="bg-violet-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-violet-[250]"
      text="bg-violet-[250]"
      textColor="light" /><BackgroundSample
      class="bg-violet-[350]"
      text="bg-violet-[350]"
      textColor="light" /><BackgroundSample
      class="bg-violet-[450]"
      text="bg-violet-[450]"
      textColor="light" /><BackgroundSample
      class="bg-violet-[550]"
      text="bg-violet-[550]"
      textColor="light" /><BackgroundSample
      class="bg-violet-[650]"
      text="bg-violet-[650]"
      textColor="light" /><BackgroundSample
      class="bg-violet-[750]"
      text="bg-violet-[750]"
      textColor="light" /><BackgroundSample
      class="bg-violet-[850]"
      text="bg-violet-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-yellow"
    ><BackgroundSample
      class="bg-yellow-[25]"
      text="bg-yellow-[25]"
      textColor="dark" /><BackgroundSample
      class="bg-yellow-[150]"
      text="bg-yellow-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-yellow-[250]"
      text="bg-yellow-[250]"
      textColor="dark" /><BackgroundSample
      class="bg-yellow-[350]"
      text="bg-yellow-[350]"
      textColor="dark" /><BackgroundSample
      class="bg-yellow-[450]"
      text="bg-yellow-[450]"
      textColor="light" /><BackgroundSample
      class="bg-yellow-[550]"
      text="bg-yellow-[550]"
      textColor="light" /><BackgroundSample
      class="bg-yellow-[650]"
      text="bg-yellow-[650]"
      textColor="light" /><BackgroundSample
      class="bg-yellow-[750]"
      text="bg-yellow-[750]"
      textColor="light" /><BackgroundSample
      class="bg-yellow-[850]"
      text="bg-yellow-[850]"
      textColor="light"
  /></SampleRow>
  <SampleRow title="bg-zinc"
    ><BackgroundSample class="bg-zinc-[25]" text="bg-zinc-[25]" textColor="dark" /><BackgroundSample
      class="bg-zinc-[150]"
      text="bg-zinc-[150]"
      textColor="dark" /><BackgroundSample
      class="bg-zinc-[250]"
      text="bg-zinc-[250]"
      textColor="dark" /><BackgroundSample
      class="bg-zinc-[350]"
      text="bg-zinc-[350]"
      textColor="light" /><BackgroundSample
      class="bg-zinc-[450]"
      text="bg-zinc-[450]"
      textColor="light" /><BackgroundSample
      class="bg-zinc-[550]"
      text="bg-zinc-[550]"
      textColor="light" /><BackgroundSample
      class="bg-zinc-[650]"
      text="bg-zinc-[650]"
      textColor="light" /><BackgroundSample
      class="bg-zinc-[750]"
      text="bg-zinc-[750]"
      textColor="light" /><BackgroundSample
      class="bg-zinc-[850]"
      text="bg-zinc-[850]"
      textColor="light"
  /></SampleRow>
</template>

<script setup lang="tsx">
const BackgroundSample = ({ text, textColor }: { text: string; textColor: 'dark' | 'light' }) => (
  <div
    class={
      'w-40 h-40 text-xs font-mono font-semibold flex items-end p-2 rounded-lg ' +
      (textColor === 'dark' ? 'text-black' : 'text-white')
    }
  >
    {text}
  </div>
)
</script>
